### ISSUE TITLE
Implement `MonadBlockchainParams` and `MonadQueryUtxo` for PSM

### ISSUE THREAD

**Issue by uhbif19** [mlabs-haskell/cem-script#14]
This issue is not dependent on any CEM state machines stuff.
Both monads are used for querying data from blockchain and should work same as regular off-chain implementation.
Datatypes used are from `cardano-api` and `PlutusLedgerApi`.

**TODO:**

- [ ] Add PSM dependency to `.cabal` and get it compiled
- [ ] Add two monads instances and PSM monad wrapper (or just use it explicitly), described below:

``` haskell
module Cardano.CEM.Monads.PSM

newtype PSMRunner = MkPSMRunner {}
instance MonadBlockchainParams PSMRunner
instance MonadQueryUtxo PSMRunner
```

**Comment by aleeusgr** [comment]
Is anyone working on this?

Thanks.

**Comment by uhbif19** [comment]
@aleeusgr Yes, done.
