### ISSUE TITLE
Initialize project repo

### ISSUE THREAD

**Issue by uhbif19** [mlabs-haskell/cem-script#3]
TODO:

- [x] Create README
- [x] Create cabal project
- [x] Add GH project and bots

**Comment by 0pdd** [comment]
@uhbif19 3 puzzles [#6](https://github.com/mlabs-haskell/cem-script/issues/6), [#8](https://github.com/mlabs-haskell/cem-script/issues/8), [#9](https://github.com/mlabs-haskell/cem-script/issues/9) are still not solved; solved: [#7](https://github.com/mlabs-haskell/cem-script/issues/7).

**Comment by 0pdd** [comment]
@uhbif19 8 puzzles [#17](https://github.com/mlabs-haskell/cem-script/issues/17), [#18](https://github.com/mlabs-haskell/cem-script/issues/18), [#19](https://github.com/mlabs-haskell/cem-script/issues/19), [#20](https://github.com/mlabs-haskell/cem-script/issues/20), [#21](https://github.com/mlabs-haskell/cem-script/issues/21), [#6](https://github.com/mlabs-haskell/cem-script/issues/6), [#8](https://github.com/mlabs-haskell/cem-script/issues/8), [#9](https://github.com/mlabs-haskell/cem-script/issues/9) are still not solved; solved: [#7](https://github.com/mlabs-haskell/cem-script/issues/7).
