### ISSUE TITLE
Make CLB back-end fast enough for fuzzing

### ISSUE THREAD

**Issue by uhbif19** [mlabs-haskell/cem-script#60]
Now one Tx sending for `Registry` takes around 0.1 seconds. This is way to much for fuzzing, we need numbers like 0.01 or 0.001.

Profiling shows that 25% is taken up `mkShelleyGlobals` in CLB (can be cached), 40% is for `makeTransactionBodyAutoBalance` and 21% is taken for `applySTSOptsEither` (real Ledger work) .

So, theoretically around 80% may be dropped with CLB. This might be okay for small and slow fuzzing about 100-1000 examples. For more we probably should use custom Ledger emulator instead of CLB. Seems like `applySTS` slow performance seem to be real, it does not seem to be only covered by Plutus (?%) or crypto (2.4%) .

TODO:

- [x] Profile CLB performance
- [x] Check CLB performance is improved by `-O`
- [ ] Support without calling `makeTransactionBodyAutoBalance` and not enforcing Tx fee
- [x] Decide if to create custom Emulator for such cases of CLB

FYI @euonymos

**Comment by uhbif19** [comment]
Actually real QD works in reasonable time, I am not sure why. >3k actions are done in ~100 seconds.

**Comment by euonymos** [comment]
I think we should think twice before getting back to a custom backend. Feel free to reopen it for further discussion.
